name: auto release develop branch

on:
  pull_request:
    branches: 
      - dev
    types: [ closed ]
  
jobs:
  if_merged:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - run: echo The PR was merged
      - run: ${{ secrets.NAME }}
      - run: ${{ secrets.PW }}
      - run: ls