name: auto release develop branch

on:
  pull_request:
    branches: 
      - dev
    types: [ closed ]
  
jobs:
  if_merged:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.REMOTE_IP }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          ls